# If you are not using Google Analytics, please change 'google-ID' to an empty string
# google-ID: x
# disqus-ID: x
# utterances-repo: x

menu:
- {name: 'About', file: ''}
- {name: 'Research', file: 'research.html'}
- {name: 'News', file: 'news.html'}
# - {name: 'CV', file: 'cv.html'}
- {name: 'CV', file: "CV.html"}

social:
- {name: 'mail', icon: 'fas fa-at', link: 'mailto:dubeyakshat07@gmail.com',
   display-link: 'dubeyakshat07@gmail.com', display-icon: "fas fa-envelope-square"}
- {name: 'github', icon: 'fab fa-github', link: 'https://github.com/dubeyakshat07', 
   display-link: 'Github', display-icon: "fab fa-github-square"}
- {name: 'twitter', icon: 'fab fa-twitter-square', link: 'https://twitter.com/AKSHATD00099862', 
   display-link: '@AKSHATD00099862', display-icon: "fab fa-twitter-square"}


publication: 
    types:
      - 'all'
      - 'workshop'
      - 'conference'
    topics:
      - {name: 'All',            id: 'all',  description: ''}

      
    default_img: "/assets/publications/placeholder.png"
    tag_list: 
      - {name: "paper",  icon: "far fa-file-pdf"}
      - {name: "website",icon: "fas fa-globe-americas"}
      - {name: "arxiv",  icon: "ai ai-arxiv"}  
      - {name: "poster", icon: "far fa-file-image"}
      - {name: "video",  icon: "fab fa-youtube"}
